### ISSUE TITLE
Without modifying any file, `harmonic build` should generate the same files

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic#148]
## Cross-platform

- [ ] #84 - Add timezone setting.
- [ ] #146 - Normalize directory separator in the generated `harmonic.js`'s `getPosts()` and `getPaths()`'s `file` property.

## Other

- [ ] #147 - Should not overwrite the existing RSS feed if nothing changed.

**Comment by UltCombo** [comment]
Although these issues are mostly minor things, the diff is really annoying when deploying the same site on different platforms.
